language: node_js
node_js:
    - "0.10"
services:
    - couchdb
env:
    global:
        - NODE_ENV=test
before_install:
    - git clone git://github.com/mycozycloud/cozy-data-system.git
    - cd cozy-data-system
    - npm install forever coffee-script casperjs -g
    - npm install #data-system
    - pwd
    - NAME=data-system TOKEN=token forever start -o forever-ds.log build/server.js
    - ps aux | grep server.js
    - sudo netstat -plunt
    - sleep 5
    - cat forever-ds.log
    - curl http://localhost:9101/
    - coffee commands.coffee test-install emails
    - cd ..
    - export NAME=emails
    - export TOKEN=apptoken
    - mkdir log
    - npm install # do it now, DovecotTesting needs it

script:
    - npm run test
    - cozy-fixtures clear Account && cozy-fixtures clear Message && cozy-fixtures clear Mailbox && cozy-fixtures load tests/fixtures
    - forever start -o casper-server.log build/server.js
    - sleep 5
    - npm run client-test-travis


after_failure:
    - cat cozy-data-system/forever-ds.log
    - cat cozy-data-system/log/test.log
